=== com-pas/compas-scl-xsd/src/main/resources/xsd/SCL2007B/IECManifest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.iec.ch/CC/2017/IECManifest" xmlns:cc="http://www.iec.ch/CC/2017/IECManifest" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.iec.ch/CC/2017/IECManifest" elementFormDefault="qualified" attributeFormDefault="unqualified" version="0.2">
	<xs:annotation>
		<xs:documentation xml:lang="en">
			COPYRIGHT (c) IEC, 2017. This version of this XSD is part of IEC copyright definition.
		</xs:documentation>
		<xs:documentation xml:lang="en">
			IEC code components will be delivered as a package including a manifest file. This Schema will describe what a package will contains
			Draft 2017-01-18 (version 0.2).
		</xs:documentation>
	</xs:annotation>
	<xs:include schemaLocation="IECCopyright.xsd"/>
	<!-- =========================================================================== -->
	<xs:simpleType name="tContentKind">
		<xs:annotation>
			<xs:documentation>Kind of content</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:Name">
			<xs:enumeration value="full"/>
			<xs:enumeration value="light"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tCategoryKind">
		<xs:annotation>
			<xs:documentation>Kind of category</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:Name">
			<xs:enumeration value="informative"/>
			<xs:enumeration value="normative"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- =========================================================================== -->
	<xs:complexType name="tNamedElement">
		<xs:annotation>
			<xs:documentation>description of one element of the code component</xs:documentation>
		</xs:annotation>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Name of the element</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="comment" type="xs:string">
			<xs:annotation>
				<xs:documentation>Free comment to describe the element</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="tFile">
		<xs:annotation>
			<xs:documentation>description of one file of the code component package</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="tNamedElement">
				<xs:attribute name="content" type="tContentKind" use="required">
					<xs:annotation>
						<xs:documentation>Type of content (full descriptive, or light for distribution)</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="category" type="tCategoryKind" use="required">
					<xs:annotation>
						<xs:documentation>Category of the element, if it is normative or informative</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="tPublication">
		<xs:annotation>
			<xs:documentation>description of the publication where the code component apply</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="tNamedElement"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="tHistoryFile">
		<xs:annotation>
			<xs:documentation>description of one history file of the code component</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="tNamedElement">
				<xs:attribute name="startingDate" type="xs:date" use="required">
					<xs:annotation>
						<xs:documentation>date when the history starts</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="endingDate" type="xs:date" use="required">
					<xs:annotation>
						<xs:documentation>date when the history ends</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="startingVersion" type="xs:string" use="required">
					<xs:annotation>
						<xs:documentation>identification of the version when the history starts</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="endingVersion" type="xs:string" use="required">
					<xs:annotation>
						<xs:documentation>identification of the version when the history ends</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="tCodeComponent">
		<xs:annotation>
			<xs:documentation>Listing of the files composing the code component of the package</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Publication" type="tPublication" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="File" type="tFile" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="HistoryFile" type="tHistoryFile" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Name of the code component</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Identifier of the code component</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="content" type="tContentKind" use="required">
			<xs:annotation>
				<xs:documentation>Type of content (full descriptive, or light for distribution)</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="date" type="xs:date" use="required">
			<xs:annotation>
				<xs:documentation>date of the code component</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="tManifest">
		<xs:annotation>
			<xs:documentation>Description the content of a package.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="tCopyrighted">
				<xs:sequence>
					<xs:element name="CodeComponent" type="tCodeComponent" minOccurs="1" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>The definition of the code components included in the package</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- =========================================================================== -->
	<xs:element name="IECManifest" type="tManifest">
		<xs:annotation>
			<xs:documentation>The manifest of a package</xs:documentation>
		</xs:annotation>
	</xs:element>
</xs:schema>

=== com-pas/compas-scl-xsd/src/xsd/SCL2007B/IECManifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<IECManifest xmlns="http://www.iec.ch/CC/2017/IECManifest" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.iec.ch/CC/2017/IECManifest IECManifest.xsd">
	<Copyright>
		<Notice>
			COPYRIGHT (c) IEC, 2017. This version of this XSD is part of IEC 61850-6:2009; see the IEC 61850-6:2009 for full legal notices. In case of any differences between the here-below code and the IEC published content, the here-below definition supersedes the IEC publication; it may contain updates. See history files. The whole document has to be taken into account to have a full description of this code component.
			See www.iec.ch/CCv1 for copyright details.
		</Notice>
		<License uri="www.iec.ch/CCv1">IEC License</License>
	</Copyright>
	<CodeComponent id="IEC_61850-6.2007B.SCL.XSD" name="IEC 61850-6 SCL schema V2007B" content="full" date="2014-01-22">
		<Publication name="IEC_61850-6.2009_ed2.0" comment="Configuration description language for communication in power utility automation systems related to IEDs"/>
		<File name="SCL.xsd" category="normative" content="full"/>
		<File name="SCL_Substation.xsd" category="normative" content="full"/>
		<File name="SCL_Communication.xsd" category="normative" content="full"/>
		<File name="SCL_IED.xsd" category="normative" content="full"/>
		<File name="SCL_DataTypeTemplates.xsd" category="normative" content="full"/>
		<File name="SCL_BaseTypes.xsd" category="normative" content="full"/>
		<File name="SCL_BaseSimpleTypes.xsd" category="normative" content="full"/>
		<File name="SCL_Enums.xsd" category="normative" content="full"/>
		<File name="SCL.Doc.HTML.zip" category="normative" content="full" comment="Zip archive containing the HTML documentation of the SCL. Contains the 'SCL.html' file and all related pictures"/>
		<HistoryFile name="history3.0.txt" startingDate="2006-04-30" endingDate="2009-07-03" startingVersion="IEC_61850-6.2.0.SCL.XSD" endingVersion="IEC_61850-6.3.0.SCL.XSD"/>
		<HistoryFile name="history.2007B.txt" startingDate="2009-12-02" endingDate="2014-01-22" startingVersion="IEC_61850-6.3.0.SCL.XSD" endingVersion="IEC_61850-6.2007B.SCL.XSD"/>
	</CodeComponent>
</IECManifest>
